version: '3.1'

services:
  php:
    container_name: www
    build: docker.bak/php
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      #- ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  db:
    container_name: db
    build: docker.bak/mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: MYSQL_ALLOW_EMPTY_PASSWORD
      MYSQL_PASSWORD: MYSQL_ALLOW_EMPTY_PASSWORD
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/db:/var/lib/mysql
volumes:
  php:
  db: